name: PR build

on:
  workflow_call:
  pull_request:

permissions:
  contents: read
  checks: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Maven Action
        uses: s4u/setup-maven-action@v1.18.0
        with:
          java-distribution: 'temurin'
          java-version: 17
          maven-version: 3.9.9
          cache-enabled: true

      - name: Maven build
        run: mvn --batch-mode --update-snapshots verify

      - name: Run Quality Monitor
        uses: uhafner/quality-monitor@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          pr-number: ${{ steps.pr.outputs.number }}
          config: > # Only evaluate test and coverage for now
            {
              "tests": {
                "name": "JUnit",
                "tools": [
                  {
                    "id": "test",
                    "name": "Tests",
                    "pattern": "**/target/*-reports/TEST*.xml"
                  }
                ]
              },
              "coverage": [
                {
                  "name": "JaCoCo",
                  "tools": [
                    {
                      "id": "jacoco",
                      "name": "Line Coverage",
                      "metric": "line",
                      "sourcePath": "src/main/java",
                      "pattern": "**/jacoco.xml"
                    }
                  ]
                }
              ]
            }
