name: updatecli
on:
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * 1' # Every Monday at 2am UTC
  push:
  pull_request:
jobs:
  updatecli:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    if: github.repository_owner == 'oras-project'
    steps:

      - name: Checkout code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false

      - name: Install Updatecli in the runner
        uses: updatecli/updatecli-action@0224b21c3687ac1a7510298d58c9a42db84e5814 # v2.92.0

      - name: Run Updatecli in Dry Run mode
        run: updatecli diff --config ./updatecli/updatecli.d --values ./updatecli/values.github-action.yaml
        env:
          UPDATECLI_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run Updatecli in Apply mode
        if: github.ref == 'refs/heads/main'
        run: updatecli apply --config ./updatecli/updatecli.d --values ./updatecli/values.github-action.yaml
        env:
          UPDATECLI_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
